---
- name: example file of blockin file mmodule.
  hosts: all
  become: true
  tasks:  
    - blockinfile
      path: /media/rohit
      create: yes
      block: 
          hello we are learning ansible on friday
          