---
- name: Update Existing Files Named 'rohit'
  hosts: all
  become: yes
  vars:
    file_name: "rohit"
    content: |
      This is the new content for the file.
      You can add multiple lines of text here.

  tasks:
    - name: Find files named 'rohit'
      find:
        paths: /media/rohit
        patterns: "{{ rohit }}"
      register: found_files

    - name: Ensure content is present in the file
      blockinfile:
        path: "{{ /media/rohit }}"
        block: "{{ content }}"
        create: yes
      loop: "{{ found_files.files }}"
      when: found_files.matched > 0
...