---
- name: Deploy Static Website
  hosts: webservers
  become: yes
  vars:
    web_root: "/var/www/html"
    index_file: "{{ web_root }}/index.html"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Upload index.html
      copy:
        content: |
          <!doctype html>
          <html>
          <head><title>Welcome</title></head>
          <body><h1>Hello, World!</h1></body>
          </html>
        dest: "{{ index_file }}"
        mode: '0644'

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
